# site settings
title: Theoretical Chemistry  
subtitle: at Virginia Tech
email: nmayhall@vt.edu
description: 
baseurl: "/vt_theory_website" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 900 West Campus Drive
city: Blacksburg 
state: VA
zip_code: 24061
country: United States of America
phone: 540-231-5391 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

include: ['_posts', '_people']




# social settings
500px_url:
facebook_url: https://www.facebook.com/VTCHEM/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vt_science?lang=env

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman